sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis
  - pip install coverage
  - pip install python-coveralls

script:
  - tox
#  - if [ $TRAVIS_PYTHON_VERSION = '3.5' ]; then coverage run --source multisite --omit multisite/migrations/*,multisite/south_migrations/*,multisite/tests.py setup.py test; fi
#
after_success:
#  # run coverage once only
#  - if [ $TRAVIS_PYTHON_VERSION = '3.5' ]; then coveralls; fi
  - coveralls